package com.mhaquirks;
import java.io.*;import java.util.*;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.potion.*;import org.bukkit.scheduler.BukkitRunnable;import org.bukkit.util.Vector;
public class MHAQuirks extends JavaPlugin implements Listener{
 Map<UUID,String> q=new HashMap<>(),side=new HashMap<>();Map<String,Long> cd=new HashMap<>();File file;YamlConfiguration data;
 static final String K="KINETIC_MANIPULATION",O="ONE_FOR_ALL",H="HALF_COLD_HALF_HOT";
 public void onEnable(){if(!getDataFolder().exists())getDataFolder().mkdirs();file=new File(getDataFolder(),"players.yml");data=YamlConfiguration.loadConfiguration(file);load();getServer().getPluginManager().registerEvents(this,this);getCommand("quirk").setExecutor(this::cmd);new BukkitRunnable(){public void run(){for(Player p:Bukkit.getOnlinePlayers())if(has(p,H)&&p.isSneaking())p.getWorld().spawnParticle("ICE".equals(side.get(p.getUniqueId()))?Particle.SNOW_SHOVEL:Particle.FLAME,p.getLocation().add(0,1,0),12,.45,.8,.45,.02);}}.runTaskTimer(this,0,5);}
 public void onDisable(){save();}
 void load(){if(data.getConfigurationSection("players")==null)return;for(String s:data.getConfigurationSection("players").getKeys(false))try{String x=data.getString("players."+s+".quirk");if(x!=null)q.put(UUID.fromString(s),x);}catch(Exception e){}}
 void save(){for(Map.Entry<UUID,String> e:q.entrySet())data.set("players."+e.getKey()+".quirk",e.getValue());try{data.save(file);}catch(Exception e){}}
 boolean has(Player p,String x){return x.equals(q.get(p.getUniqueId()));}
 boolean ready(Player p,String a,long ms){String k=p.getUniqueId()+a;Long t=cd.get(k);if(t!=null&&System.currentTimeMillis()-t<ms){p.sendMessage(ChatColor.RED+"Cooldown: "+((ms-(System.currentTimeMillis()-t)+999)/1000)+"s");return false;}cd.put(k,System.currentTimeMillis());return true;}
 ItemStack item(Material m,String n){ItemStack i=new ItemStack(m);ItemMeta im=i.getItemMeta();im.setDisplayName(ChatColor.AQUA+n);i.setItemMeta(im);return i;}
 void gui(Player p){Inventory i=Bukkit.createInventory(null,27,ChatColor.DARK_PURPLE+"Choose Your Quirk");i.setItem(10,item(Material.ENDER_PEARL,"Kinetic Manipulation"));i.setItem(13,item(Material.NETHER_STAR,"One For All"));i.setItem(16,item(Material.BLAZE_POWDER,"Half-Cold Half-Hot"));p.openInventory(i);}
 void set(Player p,String x){q.put(p.getUniqueId(),x);save();p.sendMessage(ChatColor.GREEN+"Quirk selected: "+x);loadout(p);}
 void loadout(Player p){p.getInventory().clear();String x=q.get(p.getUniqueId());if(K.equals(x)){p.getInventory().setItem(0,item(Material.NETHER_STAR,"Kinetic Burst"));p.getInventory().setItem(1,item(Material.IRON_INGOT,"Acceleration"));p.getInventory().setItem(2,item(Material.IRON_BLOCK,"Deceleration"));p.getInventory().setItem(3,item(Material.ENDER_PEARL,"Infinite Approach"));}else if(O.equals(x)){p.getInventory().setItem(0,item(Material.NETHER_STAR,"Smash"));p.getInventory().setItem(1,item(Material.IRON_BLOCK,"Detroit Smash"));p.getInventory().setItem(2,item(Material.FEATHER,"Full Cowl"));}else if(H.equals(x)){p.getInventory().setItem(0,item(Material.BLAZE_POWDER,"Half-Cold Half-Hot"));p.getInventory().setItem(1,item(Material.ICE,"Ice Spike"));p.getInventory().setItem(2,item(Material.PACKED_ICE,"Ice Wall"));p.getInventory().setItem(3,item(Material.FIREBALL,"Flame Blast"));p.getInventory().setItem(4,item(Material.SNOWBALL,"Flashfire Frost"));side.put(p.getUniqueId(),"FIRE");}}
 @EventHandler public void click(InventoryClickEvent e){if(!e.getView().getTitle().equals(ChatColor.DARK_PURPLE+"Choose Your Quirk"))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player))return;Player p=(Player)e.getWhoClicked();ItemStack i=e.getCurrentItem();if(i==null||!i.hasItemMeta())return;String n=i.getItemMeta().getDisplayName();if(n.contains("Kinetic"))set(p,K);else if(n.contains("One For All"))set(p,O);else if(n.contains("Half-Cold"))set(p,H);p.closeInventory();}
 @EventHandler public void interact(PlayerInteractEvent e){Player p=e.getPlayer();Action a=e.getAction();if(a!=Action.RIGHT_CLICK_AIR&&a!=Action.RIGHT_CLICK_BLOCK&&a!=Action.LEFT_CLICK_AIR&&a!=Action.LEFT_CLICK_BLOCK)return;ItemStack i=p.getInventory().getItemInMainHand();if(i==null||!i.hasItemMeta())return;String n=i.getItemMeta().getDisplayName();
  if(has(p,H)&&n.contains("Half-Cold Half-Hot")){if(p.isSneaking()&&a.name().startsWith("LEFT")){side.put(p.getUniqueId(),"FIRE");p.sendMessage(ChatColor.RED+"Fire side selected");e.setCancelled(true);return;}if(p.isSneaking()&&a.name().startsWith("RIGHT")){side.put(p.getUniqueId(),"ICE");p.sendMessage(ChatColor.AQUA+"Ice side selected");e.setCancelled(true);return;}if(!p.isSneaking()&&a.name().startsWith("RIGHT")){if("ICE".equals(side.get(p.getUniqueId())))ice(p);else fire(p);e.setCancelled(true);return;}}
  if(has(p,K)&&n.contains("Kinetic Burst")&&right(a))burst(p);else if(has(p,K)&&n.contains("Acceleration")&&right(a))acc(p);else if(has(p,K)&&n.contains("Deceleration")&&right(a))dec(p);else if(has(p,K)&&n.contains("Infinite Approach")&&right(a))inf(p);
  else if(has(p,O)&&n.contains("Detroit Smash")&&right(a))det(p);else if(has(p,O)&&n.equals(ChatColor.AQUA+"Smash")&&right(a))smash(p);else if(has(p,O)&&n.contains("Full Cowl")&&right(a))cowl(p);
  else if(has(p,H)&&n.contains("Ice Spike")&&right(a))iceSpike(p);else if(has(p,H)&&n.contains("Ice Wall")&&right(a))iceWall(p);else if(has(p,H)&&n.contains("Flame Blast")&&right(a))fire(p);else if(has(p,H)&&n.contains("Flashfire Frost")&&right(a))frost(p);
 }
 boolean right(Action a){return a==Action.RIGHT_CLICK_AIR||a==Action.RIGHT_CLICK_BLOCK;}
 void fire(Player p){if(!ready(p,"fire",1200))return;SmallFireball f=p.launchProjectile(SmallFireball.class);f.setMetadata("MHA_FIRE",new org.bukkit.metadata.FixedMetadataValue(this,true));p.getWorld().playSound(p.getLocation(),Sound.ENTITY_BLAZE_SHOOT,1,1);}
 void ice(Player p){if(!ready(p,"ice",1200))return;Snowball s=p.launchProjectile(Snowball.class);s.setMetadata("MHA_ICE",new org.bukkit.metadata.FixedMetadataValue(this,true));}
 @EventHandler public void hit(EntityDamageByEntityEvent e){if(!(e.getDamager() instanceof Projectile)||!(e.getEntity() instanceof LivingEntity))return;Projectile pr=(Projectile)e.getDamager();LivingEntity t=(LivingEntity)e.getEntity();if(pr.hasMetadata("MHA_FIRE")){t.setFireTicks(80);e.setDamage(5);}if(pr.hasMetadata("MHA_ICE")){t.addPotionEffect(new PotionEffect(PotionEffectType.SLOW,100,4));t.addPotionEffect(new PotionEffect(PotionEffectType.JUMP,100,128));e.setDamage(1);}}
 void burst(Player p){if(!ready(p,"kb",2500))return;for(Entity e:p.getNearbyEntities(5,3,5))if(e instanceof LivingEntity&&e!=p){Vector v=e.getLocation().toVector().subtract(p.getLocation().toVector()).normalize().multiply(1.7);v.setY(.6);e.setVelocity(v);((LivingEntity)e).damage(4,p);}p.getWorld().spawnParticle(Particle.CRIT_MAGIC,p.getLocation(),30,1,1,1,.1);}
 void acc(Player p){if(!ready(p,"acc",1500))return;p.setVelocity(p.getLocation().getDirection().multiply(1.8).setY(.2));}
 void dec(Player p){if(!ready(p,"dec",1500))return;p.setVelocity(new Vector(0,0,0));}
 void inf(Player p){if(!ready(p,"inf",5000))return;for(Entity e:p.getNearbyEntities(8,4,8))if(e instanceof Projectile)e.setVelocity(new Vector(0,0,0));p.sendMessage(ChatColor.LIGHT_PURPLE+"Infinite Approach active.");}
 void smash(Player p){if(!ready(p,"smash",1800))return;for(Entity e:p.getNearbyEntities(4,2,4))if(e instanceof LivingEntity&&e!=p)((LivingEntity)e).damage(6,p);}
 void det(Player p){if(!ready(p,"det",6000))return;for(Entity e:p.getNearbyEntities(7,3,7))if(e instanceof LivingEntity&&e!=p){((LivingEntity)e).damage(12,p);e.setVelocity(e.getLocation().toVector().subtract(p.getLocation().toVector()).normalize().multiply(2.3).setY(1));}}
 void cowl(Player p){if(!ready(p,"cowl",12000))return;p.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,240,1));p.addPotionEffect(new PotionEffect(PotionEffectType.JUMP,240,1));}
 void iceSpike(Player p){if(!ready(p,"spike",2200))return;p.getWorld().spawnParticle(Particle.SNOW_SHOVEL,p.getTargetBlock((Set<Material>)null,12).getLocation().add(0,1,0),40,.5,.5,.5,.02);}
 void iceWall(Player p){if(!ready(p,"wall",5000))return;p.getWorld().spawnParticle(Particle.SNOW_SHOVEL,p.getTargetBlock((Set<Material>)null,8).getLocation().add(0,1,0),80,1,1,1,.02);}
 void frost(Player p){if(!ready(p,"frost",5000))return;for(Entity e:p.getNearbyEntities(6,3,6))if(e instanceof LivingEntity&&e!=p){((LivingEntity)e).damage(4,p);((LivingEntity)e).addPotionEffect(new PotionEffect(PotionEffectType.SLOW,120,3));}p.getWorld().spawnParticle(Particle.SNOW_SHOVEL,p.getLocation(),40,1,1,1,.1);}
 public boolean cmd(CommandSender s,String l,String[] a){if(!(s instanceof Player))return true;Player p=(Player)s;if(a.length==0||a[0].equalsIgnoreCase("select"))gui(p);else if(a[0].equalsIgnoreCase("loadout"))loadout(p);else if(a[0].equalsIgnoreCase("list")){p.sendMessage(ChatColor.GOLD+"Quirks: Kinetic Manipulation | One For All | Half-Cold Half-Hot");}else if(a[0].equalsIgnoreCase("set")&&a.length>=3&&p.hasPermission("mhaquirks.admin")){Player t=Bukkit.getPlayer(a[1]);if(t==null)return true;String x=a[2].toUpperCase();if(x.equals("KINETIC"))x=K;else if(x.equals("ONE_FOR_ALL"))x=O;else if(x.equals("HALF_COLD_HALF_HOT"))x=H;set(t,x);}return true;}
}